name: Update Gradle Wrapper

on:
  workflow_dispatch:
    tags:
      description: 'Update manually'
  schedule:
    - cron: "30 6 * * SAT"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
